version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-www}'
        image: talos/app
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER:-www}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - ./:/var/www/talos
        networks:
            - talos
        depends_on:
            - db
            - redis
            - meilisearch
            - minio
            - selenium

    nginx:
        image: nginx:1.21-alpine
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/talos
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_TLS_PORT:-443}:443'
        networks:
            - talos

    db:
        image: postgres:14
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'db-data:/var/lib/postgresql/data'
        networks:
            - talos
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s

    redis:
        image: redis:7
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis-data:/data'
        networks:
            - talos
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    meilisearch:
        image: getmeili/meilisearch:v0.26.1
        restart: unless-stopped
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'meilisearch-data:/data.ms'
        networks:
            - talos
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s

    minio:
        image: minio/minio:latest
        restart: unless-stopped
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
        volumes:
            - 'minio-data:/data/minio'
        networks:
            - talos
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s

    selenium:
        image: selenium/standalone-chrome:101.0
        restart: unless-stopped
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - talos


    mailhog:
        image: mailhog/mailhog:v1.0.1
        restart: unless-stopped
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - talos

networks:
    talos:
        driver: bridge

volumes:
    db-data:
        driver: local
    redis-data:
        driver: local
    meilisearch-data:
        driver: local
    minio-data:
        driver: local
